baseURL = 'http://makaronia.me/'
languageCode = 'gr-GR'
defaultContentLanguage = "gr"
defaultContentLang = "gr"
title = 'Μακαρόνια με...'
theme = 'cupper-hugo-theme'
copyright = ''

[permalinks]
  posts = '/:title/'

[Params]
navTitleText = ""
description = "Ένα Μπλόγκ που δε σχετίζεται καθόλου με μακαρόνια"
moveFooterToHeader = true

custom_css = [
	"/css/paper.css",
	"/css/makaroniame.css",
	"/css/animations.css",
	"/css/text-vide.css",
	]
custom_js = [
	"/js/text-vide.1.6.2.min.js",
	"/js/text-vide.control.js",
]

[ markup.goldmark.extensions]
    table = true

[[menu.nav]]
name = "Μπλόγκ"
url = "/"
weight = 1

[[menu.nav]]
name = "Βιβλίο!"
url = "/davesara/"
weight = 2

[[menu.nav]]
name = "Κόνσεπτ"
url = "/concept/"
weight = 3

[[menu.nav]]
name = "Επικοινωνία"
url = "/epikoinwnia/"
weight = 4

#[[menu.nav]]
#name = "Άρεσές"
#url = "/index.xml"
#weight = 4
