baseURL = 'http://makaronia.me/'
languageCode = 'gr-GR'
defaultContentLanguage = "gr"
defaultContentLang = "gr"
title = 'Μακαρόνια με...'
theme = 'cupper-hugo-theme'
copyright = ''
disableAliases = false


[permalinks]
  posts = '/:title/'

[Params]
navTitleText = ""
description = "Ένα Μπλόγκ που δε σχετίζεται καθόλου με μακαρόνια"
moveFooterToHeader = true
googleAnalyticsID = "G-RMBG2TDS3X"

custom_css = [
	"/css/paper.css",
	"/css/makaroniame.css",
	"/css/animations.css",
	"/css/text-vide.css",
	]

custom_js = [
	"/js/text-vide.1.6.2.min.js",
	"/js/text-vide.control.js",
	"/js/dark-theme.control.js",
	"/js/onload.js",
]

[ markup.goldmark.extensions ]
    table = true

[[menu.nav]]
name = "Μπλόγκ"
url = "/"
weight = 1

[[menu.nav]]
name = "Βιβλίο!"
url = "/davesara/"
weight = 2

[[menu.nav]]
name = "Γιουτχιούμπ!"
url = "https://youtube.com/@makaroniame"
weight = 3

[[menu.nav]]
name = "Κόνσεπτ"
url = "/concept/"
weight = 4

[[menu.nav]]
name = "Επικοινωνία"
url = "/epikoinwnia/"
weight = 5

#[[menu.nav]]
#name = "Άρεσές"
#url = "/index.xml"
#weight = 6
